backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "office" # Used in routes, e.g., /admin/collections/blog
    label: "Contact - Offices" # Used in the UI
    folder: "content/offices" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Address2", name: "address2", widget: "string"}
      - {label: "Office #", name: "office", widget: "string"}
      - {label: "Fax #", name: "fax", widget: "string"}
      - {label: "Map Url", name: "map", widget: "string"}
  - name: "contact" # Used in routes, e.g., /admin/collections/blog
    label: "Contact - Direct Contact" # Used in the UI
    folder: "content/contacts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Phone", name: "phone", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}

  - name: "careers-contents" # Used in routes, e.g., /admin/collections/blog
    label: "Careers - Postings" # Used in the UI
    folder: "content/career/postings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Last Updated", name: "updated", widget: "date", format: "MMM Do YY"}
      - {label: "Position type(full/part time)", name: "type", widget: "string"}
      - {label: "Weekly Hours", name: "hours", widget: "string"}
      - {label: "Location", name: "location", widget: "string"} 
      - {label: "Description", name: "desc", widget: "markdown"}
      - {label: "Knowledge Skills and Abilities", name: "knowledge", widget: "markdown", required: false}
      - {label: "Minimum Job Requirements", name: "requirements", widget: "markdown", required: false}
      - {label: "Duties & Responsibilities", name: "duties", widget: "markdown", required: false} 
      - label: "Pages"
        name: "pages"
        files:
          - label: "Contact Page"
            name: "contactpage"
            file: "content/contact.yml"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - label: Team
                name: team
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Position, name: position, widget: string}
                  - {label: Photo, name: photo, widget: image}
          - label: "Careers Page"
            name: "careerspage"
            file: "content/career.yml"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - label: Locations
                name: locations
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Address, name: address, widget: string}